### ISSUE TITLE
unable to save exported xml files (plane)

### ISSUE THREAD

**Issue by monkeypants** [TLmaK0/avl-editor#2]
using same system described in #1, after loading sample/plane.crr, when I try to export crrcsim file to sample/plane.xml it "silently" fails (no feedback in the UI - as though it worked fine - but no saved file either).

In the terminal where I started "java -jar CRRCsimEditor.jar" the STDERR complained that there is no file "/tmp/chrrcsim_8081677161215649493/crrcsim_tmp.st" and this is true, there is no such file. The tmp directory does exist and contains `crrcsim_tmp.avl`, `crrcsim_tmp.mass` and `crrcsim_tmp.run` files, just not the crrcsim_tmp.st file.

This is the STDERR message:

```
Feb 24, 2015 10:49:40 PM com.abajar.crrcsimeditor.CRRCsimEditor exportAsCRRCsim
SEVERE: /tmp/chrrcsim_8081677161215649493/crrcsim_tmp.st (No such file or directory)
java.io.FileNotFoundException: /tmp/chrrcsim_8081677161215649493/crrcsim_tmp.st (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at com.abajar.crrcsimeditor.avl.connectivity.AvlRunner.run(AvlRunner.java:121)
    at com.abajar.crrcsimeditor.avl.connectivity.AvlRunner.<init>(AvlRunner.java:68)
    at com.abajar.crrcsimeditor.crrcsim.AeroFactory.createFromAvl(AeroFactory.java:23)
    at com.abajar.crrcsimeditor.crrcsim.CRRCSim.calculate(CRRCSim.java:188)
    at com.abajar.crrcsimeditor.CRRCsimEditor.exportAsCRRCsim(CRRCsimEditor.java:244)
    at com.abajar.crrcsimeditor.CRRCsimEditor.exportAsCRRCsim(CRRCsimEditor.java:234)
    at com.abajar.crrcsimeditor.MainFrame.fileExportAsCRRsimMenuItemActionPerformed(MainFrame.java:644)
    at com.abajar.crrcsimeditor.MainFrame.access$2600(MainFrame.java:50)
    at com.abajar.crrcsimeditor.MainFrame$26.actionPerformed(MainFrame.java:558)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
    at java.awt.Component.processMouseEvent(Component.java:6505)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
    at java.awt.Component.processEvent(Component.java:6270)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4861)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at com.abajar.crrcsimeditor.MainFrame$26.actionPerformed(MainFrame.java:558)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
    at java.awt.Component.processMouseEvent(Component.java:6505)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
    at java.awt.Component.processEvent(Component.java:6270)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4861)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:708)
    at java.awt.EventQueue$4.run(EventQueue.java:706)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by TLmaK0** [comment]
Thanks @monkeypants, I will check it. I appreciate your help to make this work.

**Comment by monkeypants** [comment]
I'm still getting this problem, using the latest sources and `sbt run` invocation. Even after `sbt clean` etc.

**Comment by TLmaK0** [comment]
Do you have the same problem with the new sample/plane.crr without doing any change?
This normally happens when AVL is unable to calculate Stability derivatives. I will reopen the problem until we provide a correct message alert.
